apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springcc
  template:
    metadata:
      labels:
        app: springcc
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: springcc
        image: redis
        ports:
        - containerPort: 8888
          name: springcc
---
apiVersion: v1
kind: Service
metadata:
  name: springcc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: springcc
